services:
  main-api:
    build:
      context: .
      dockerfile: ./apps/main-api/Dockerfile
      target: development
      tags:
        - main-api
    command: pnpm run start:dev main-api
    env_file:
      - ./apps/main-api/.env
    depends_on:
      - auth
      - aggregators
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
      tags:
        - auth
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'

  aggregators:
    build:
      context: .
      dockerfile: ./apps/aggregators/Dockerfile
      target: development
      tags:
        - aggregators
    command: pnpm run start:dev aggregators
    env_file:
      - ./apps/aggregators/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'