services:
  main-api:
    build:
      context: .
      dockerfile: ./apps/main-api/Dockerfile
      target: development
    command: pnpm run start:dev main-api
    env_file:
      - ./apps/main-api/.env
    # depends_on:
    #   - billing
    #   - auth
    #   - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
